=== PLCoster/ubc_softdev_capstone/test/query.schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "title": "Test Query",
    "description": "A test query and its expected response when passed to InsightFacade.performQuery",
    "type": "object",
    "properties": {
        "title": {
            "description": "A meaningful test name that describes the query",
            "type": "string",
            "minLength": 5,
            "maxLength": 100
        },
        "queryString": {
            "description": "The query string that will be sent to performQuery"
        },
        "queryAST": {
            "description": "The equivalent query in EBNF AST Object format - note that not every string query has an equivalent AST"
        },
        "response": {
            "description": "The expected response from performQuery",
            "type": "object",
            "properties": {
                "code": {
                    "type": "number"
                },
                "body": {
                    "type": "object"
                }
            },
            "additionalProperties": false,
            "required": ["code", "body"]
        }
    },
    "additionalProperties": false,
    "required": ["title", "queryString", "response"]
}

=== PLCoster/ubc_softdev_capstone/test/queries/exq4.json
{
    "title": "A query with invalid sort key",
    "queryString": "In rooms dataset abc, find entries whose Seats is greater than 80; show Seats and Address; sort in ascending order by Average2.",
    "response": {
        "code": 400,
        "body": {
            "error": ""
        }
    },
    "queryAST": {
        "ID": "abc",
        "KIND": "rooms",
        "WHERE": { "GT": { "rooms_seats": 80 } },
        "OPTIONS": {
            "COLUMNS": ["rooms_seats", "rooms_address"],
            "ORDER": { "dir": "UP", "keys": ["Average2"] }
        }
    }
}

=== PLCoster/ubc_softdev_capstone/test/queries/courses/two_entry_queries/simple_order_queries/q2_two_all_id_asc.json
{
    "title": "SELECT * FROM coursesTwoEntries, ORDER BY id ASC",
    "queryString": "In courses dataset coursesTwoEntries, find all entries; show Audit, Average, Department, Fail, ID, Instructor, Pass, Title and UUID; sort in ascending order by ID.",
    "response": {
        "code": 200,
        "body": {
            "result": [
                {
                    "coursesTwoEntries_audit": 0,
                    "coursesTwoEntries_avg": 86.65,
                    "coursesTwoEntries_dept": "adhe",
                    "coursesTwoEntries_fail": 0,
                    "coursesTwoEntries_id": "327",
                    "coursesTwoEntries_instructor": "smulders, dave",
                    "coursesTwoEntries_pass": 23,
                    "coursesTwoEntries_title": "teach adult",
                    "coursesTwoEntries_uuid": "17255"
                },
                {
                    "coursesTwoEntries_audit": 10,
                    "coursesTwoEntries_avg": 80.13,
                    "coursesTwoEntries_dept": "phar",
                    "coursesTwoEntries_fail": 25,
                    "coursesTwoEntries_id": "454",
                    "coursesTwoEntries_instructor": "carr, roxane",
                    "coursesTwoEntries_pass": 221,
                    "coursesTwoEntries_title": "ped geri drg thp",
                    "coursesTwoEntries_uuid": "83080"
                }
            ]
        }
    },
    "queryAST": {
        "ID": "coursesTwoEntries",
        "KIND": "courses",
        "WHERE": {},
        "OPTIONS": {
            "COLUMNS": [
                "coursesTwoEntries_audit",
                "coursesTwoEntries_avg",
                "coursesTwoEntries_dept",
                "coursesTwoEntries_fail",
                "coursesTwoEntries_id",
                "coursesTwoEntries_instructor",
                "coursesTwoEntries_pass",
                "coursesTwoEntries_title",
                "coursesTwoEntries_uuid"
            ],
            "ORDER": { "dir": "UP", "keys": ["coursesTwoEntries_id"] }
        }
    }
}
