=== PLCoster/ubc_softdev_capstone/test/query.schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "title": "Test Query",
    "description": "A test query and its expected response when passed to InsightFacade.performQuery",
    "type": "object",
    "properties": {
        "title": {
            "description": "A meaningful test name that describes the query",
            "type": "string",
            "minLength": 5,
            "maxLength": 100
        },
        "queryString": {
            "description": "The query string that will be sent to performQuery"
        },
        "queryAST": {
            "description": "The equivalent query in EBNF AST Object format - note that not every string query has an equivalent AST"
        },
        "response": {
            "description": "The expected response from performQuery",
            "type": "object",
            "properties": {
                "code": {
                    "type": "number"
                },
                "body": {
                    "type": "object"
                }
            },
            "additionalProperties": false,
            "required": ["code", "body"]
        }
    },
    "additionalProperties": false,
    "required": ["title", "queryString", "response"]
}

=== PLCoster/ubc_softdev_capstone/test/queries/courses/single_entry_queries/q1_single_uuid.json
{
    "title": "SELECT uuid FROM coursesSingleEntry",
    "queryString": "In courses dataset coursesSingleEntry, find all entries; show UUID.",
    "response": {
        "code": 200,
        "body": { "result": [{ "coursesSingleEntry_uuid": "17255" }] }
    },
    "queryAST": {
        "ID": "coursesSingleEntry",
        "KIND": "courses",
        "WHERE": {},
        "OPTIONS": { "COLUMNS": ["coursesSingleEntry_uuid"] }
    }
}

=== PLCoster/ubc_softdev_capstone/test/queries/rooms/single_room_queries/r1_single_href.json
{
    "title": "SELECT href FROM roomsSingleRoom",
    "queryString": "In rooms dataset roomsSingleRoom, find all entries; show Link.",
    "response": {
        "code": 200,
        "body": {
            "result": [
                {
                    "roomsSingleRoom_href": "http://students.ubc.ca/campus/discover/buildings-and-classrooms/room/AERL-120"
                }
            ]
        }
    },
    "queryAST": {
        "ID": "roomsSingleRoom",
        "KIND": "rooms",
        "WHERE": {},
        "OPTIONS": { "COLUMNS": ["roomsSingleRoom_href"] }
    }
}

=== PLCoster/ubc_softdev_capstone/test/queries/rooms/single_room_queries/r1_single_furniture.json
{
    "title": "SELECT furniture FROM roomsSingleRoom",
    "queryString": "In rooms dataset roomsSingleRoom, find all entries; show Furniture.",
    "response": {
        "code": 200,
        "body": {
            "result": [
                { "roomsSingleRoom_furniture": "Classroom-Fixed Tablets" }
            ]
        }
    },
    "queryAST": {
        "ID": "roomsSingleRoom",
        "KIND": "rooms",
        "WHERE": {},
        "OPTIONS": { "COLUMNS": ["roomsSingleRoom_furniture"] }
    }
}

=== PLCoster/ubc_softdev_capstone/test/queries/rooms/two_rooms_queries/simple_order_queries/r2_two_all_type_desc.json
{
    "title": "SELECT * FROM roomsTwoRooms ORDER BY seats DESC",
    "queryString": "In rooms dataset roomsTwoRooms, find all entries; show Full Name, Short Name, Number, Name, Address, Type, Furniture, Link, Latitude, Longitude and Seats; sort in descending order by Type.",
    "response": {
        "code": 200,
        "body": {
            "result": [
                {
                    "roomsTwoRooms_fullname": "Aquatic Ecosystems Research Laboratory",
                    "roomsTwoRooms_shortname": "AERL",
                    "roomsTwoRooms_number": "120",
                    "roomsTwoRooms_name": "AERL_120",
                    "roomsTwoRooms_address": "2202 Main Mall",
                    "roomsTwoRooms_lat": 49.26372,
                    "roomsTwoRooms_lon": -123.25099,
                    "roomsTwoRooms_seats": 144,
                    "roomsTwoRooms_type": "Tiered Large Group",
                    "roomsTwoRooms_furniture": "Classroom-Fixed Tablets",
                    "roomsTwoRooms_href": "http://students.ubc.ca/campus/discover/buildings-and-classrooms/room/AERL-120"
                },
                {
                    "roomsTwoRooms_fullname": "Allard Hall (LAW)",
                    "roomsTwoRooms_shortname": "ALRD",
                    "roomsTwoRooms_number": "105",
                    "roomsTwoRooms_name": "ALRD_105",
                    "roomsTwoRooms_address": "1822 East Mall",
                    "roomsTwoRooms_lat": 49.2699,
                    "roomsTwoRooms_lon": -123.25318,
                    "roomsTwoRooms_seats": 94,
                    "roomsTwoRooms_type": "Case Style",
                    "roomsTwoRooms_furniture": "Classroom-Fixed Tables/Movable Chairs",
                    "roomsTwoRooms_href": "http://students.ubc.ca/campus/discover/buildings-and-classrooms/room/ALRD-105"
                }
            ]
        }
    },
    "queryAST": {
        "ID": "roomsTwoRooms",
        "KIND": "rooms",
        "WHERE": {},
        "OPTIONS": {
            "COLUMNS": [
                "roomsTwoRooms_fullname",
                "roomsTwoRooms_shortname",
                "roomsTwoRooms_number",
                "roomsTwoRooms_name",
                "roomsTwoRooms_address",
                "roomsTwoRooms_type",
                "roomsTwoRooms_furniture",
                "roomsTwoRooms_href",
                "roomsTwoRooms_lat",
                "roomsTwoRooms_lon",
                "roomsTwoRooms_seats"
            ],
            "ORDER": { "dir": "DOWN", "keys": ["roomsTwoRooms_type"] }
        }
    }
}

=== PLCoster/ubc_softdev_capstone/test/queries/exq1_courseslarge.json
{
    "title": "SELECT dept, avg WHERE avg > 97",
    "queryString": "In courses dataset courseslarge, find entries whose Average is greater than 97; show Department and Average; sort in ascending order by Average.",
    "response": {
        "code": 200,
        "body": {
            "result": [
                { "courseslarge_dept": "math", "courseslarge_avg": 97.09 },
                { "courseslarge_dept": "math", "courseslarge_avg": 97.09 },
                { "courseslarge_dept": "epse", "courseslarge_avg": 97.09 },
                { "courseslarge_dept": "epse", "courseslarge_avg": 97.09 },
                { "courseslarge_dept": "math", "courseslarge_avg": 97.25 },
                { "courseslarge_dept": "math", "courseslarge_avg": 97.25 },
                { "courseslarge_dept": "epse", "courseslarge_avg": 97.29 },
                { "courseslarge_dept": "epse", "courseslarge_avg": 97.29 },
                { "courseslarge_dept": "nurs", "courseslarge_avg": 97.33 },
                { "courseslarge_dept": "nurs", "courseslarge_avg": 97.33 },
                { "courseslarge_dept": "epse", "courseslarge_avg": 97.41 },
                { "courseslarge_dept": "epse", "courseslarge_avg": 97.41 },
                { "courseslarge_dept": "cnps", "courseslarge_avg": 97.47 },
                { "courseslarge_dept": "cnps", "courseslarge_avg": 97.47 },
                { "courseslarge_dept": "math", "courseslarge_avg": 97.48 },
                { "courseslarge_dept": "math", "courseslarge_avg": 97.48 },
                { "courseslarge_dept": "educ", "courseslarge_avg": 97.5 },
                { "courseslarge_dept": "nurs", "courseslarge_avg": 97.53 },
                { "courseslarge_dept": "nurs", "courseslarge_avg": 97.53 },
                { "courseslarge_dept": "epse", "courseslarge_avg": 97.67 },
                { "courseslarge_dept": "epse", "courseslarge_avg": 97.69 },
                { "courseslarge_dept": "epse", "courseslarge_avg": 97.78 },
                { "courseslarge_dept": "crwr", "courseslarge_avg": 98 },
                { "courseslarge_dept": "crwr", "courseslarge_avg": 98 },
                { "courseslarge_dept": "epse", "courseslarge_avg": 98.08 },
                { "courseslarge_dept": "nurs", "courseslarge_avg": 98.21 },
                { "courseslarge_dept": "nurs", "courseslarge_avg": 98.21 },
                { "courseslarge_dept": "epse", "courseslarge_avg": 98.36 },
                { "courseslarge_dept": "epse", "courseslarge_avg": 98.45 },
                { "courseslarge_dept": "epse", "courseslarge_avg": 98.45 },
                { "courseslarge_dept": "nurs", "courseslarge_avg": 98.5 },
                { "courseslarge_dept": "nurs", "courseslarge_avg": 98.5 },
                { "courseslarge_dept": "nurs", "courseslarge_avg": 98.58 },
                { "courseslarge_dept": "nurs", "courseslarge_avg": 98.58 },
                { "courseslarge_dept": "epse", "courseslarge_avg": 98.58 },
                { "courseslarge_dept": "epse", "courseslarge_avg": 98.58 },
                { "courseslarge_dept": "epse", "courseslarge_avg": 98.7 },
                { "courseslarge_dept": "nurs", "courseslarge_avg": 98.71 },
                { "courseslarge_dept": "nurs", "courseslarge_avg": 98.71 },
                { "courseslarge_dept": "eece", "courseslarge_avg": 98.75 },
                { "courseslarge_dept": "eece", "courseslarge_avg": 98.75 },
                { "courseslarge_dept": "epse", "courseslarge_avg": 98.76 },
                { "courseslarge_dept": "epse", "courseslarge_avg": 98.76 },
                { "courseslarge_dept": "epse", "courseslarge_avg": 98.8 },
                { "courseslarge_dept": "spph", "courseslarge_avg": 98.98 },
                { "courseslarge_dept": "spph", "courseslarge_avg": 98.98 },
                { "courseslarge_dept": "cnps", "courseslarge_avg": 99.19 },
                { "courseslarge_dept": "math", "courseslarge_avg": 99.78 },
                { "courseslarge_dept": "math", "courseslarge_avg": 99.78 }
            ]
        }
    },
    "queryAST": {
        "ID": "courseslarge",
        "KIND": "courses",
        "WHERE": { "GT": { "courseslarge_avg": 97 } },
        "OPTIONS": {
            "COLUMNS": ["courseslarge_dept", "courseslarge_avg"],
            "ORDER": { "dir": "UP", "keys": ["courseslarge_avg"] }
        }
    }
}

=== PLCoster/ubc_softdev_capstone/test/queries/courses/four_entry_queries/group_by_queries/q4_four_all_group_by_dept_title_avg.json
{
    "title": "SELECT dept, title, avg FROM coursesFourEntries GROUP BY dept, title, avg",
    "queryString": "In courses dataset coursesFourEntries grouped by Department, Title and Average, find all entries; show Department, Title and Average.",
    "response": {
        "code": 200,
        "body": {
            "result": [
                {
                    "coursesFourEntries_dept": "adhe",
                    "coursesFourEntries_title": "teach adult",
                    "coursesFourEntries_avg": 86.65
                },
                {
                    "coursesFourEntries_dept": "adhe",
                    "coursesFourEntries_title": "teach adult",
                    "coursesFourEntries_avg": 78.93
                },
                {
                    "coursesFourEntries_dept": "phar",
                    "coursesFourEntries_title": "ped geri drg thp",
                    "coursesFourEntries_avg": 80.13
                },
                {
                    "coursesFourEntries_dept": "phar",
                    "coursesFourEntries_title": "ped geri drg thp",
                    "coursesFourEntries_avg": 75.3
                }
            ]
        }
    },
    "queryAST": {
        "ID": "coursesFourEntries",
        "KIND": "courses",
        "WHERE": {},
        "OPTIONS": {
            "COLUMNS": [
                "coursesFourEntries_dept",
                "coursesFourEntries_title",
                "coursesFourEntries_avg"
            ]
        },
        "TRANSFORMATIONS": {
            "GROUP": [
                "coursesFourEntries_dept",
                "coursesFourEntries_title",
                "coursesFourEntries_avg"
            ]
        }
    }
}

=== PLCoster/ubc_softdev_capstone/test/queries/courses/two_entry_queries/single_criteria_queries/q2_two_instructor_is_not.json
{
    "title": "SELECT * FROM coursesTwoEntries, WHERE instructor!='smulders, dave', ORDER BY id ASC",
    "queryString": "In courses dataset coursesTwoEntries, find entries whose Instructor is not \"smulders, dave\"; show Audit, Average, Department, Fail, ID, Instructor, Pass, Title and UUID; sort in ascending order by ID.",
    "response": {
        "code": 200,
        "body": {
            "result": [
                {
                    "coursesTwoEntries_audit": 10,
                    "coursesTwoEntries_avg": 80.13,
                    "coursesTwoEntries_dept": "phar",
                    "coursesTwoEntries_fail": 25,
                    "coursesTwoEntries_id": "454",
                    "coursesTwoEntries_instructor": "carr, roxane",
                    "coursesTwoEntries_pass": 221,
                    "coursesTwoEntries_title": "ped geri drg thp",
                    "coursesTwoEntries_uuid": "83080"
                }
            ]
        }
    },
    "queryAST": {
        "ID": "coursesTwoEntries",
        "KIND": "courses",
        "WHERE": {
            "NOT": {
                "IS": { "coursesTwoEntries_instructor": "smulders, dave" }
            }
        },
        "OPTIONS": {
            "COLUMNS": [
                "coursesTwoEntries_audit",
                "coursesTwoEntries_avg",
                "coursesTwoEntries_dept",
                "coursesTwoEntries_fail",
                "coursesTwoEntries_id",
                "coursesTwoEntries_instructor",
                "coursesTwoEntries_pass",
                "coursesTwoEntries_title",
                "coursesTwoEntries_uuid"
            ],
            "ORDER": { "dir": "UP", "keys": ["coursesTwoEntries_id"] }
        }
    }
}

=== PLCoster/ubc_softdev_capstone/test/queries/courses/single_entry_queries/q1_single_year.json
{
    "title": "SELECT * FROM coursesSingleEntry",
    "queryString": "In courses dataset coursesSingleEntry, find all entries; show Year.",
    "response": {
        "code": 200,
        "body": { "result": [{ "coursesSingleEntry_year": 2010 }] }
    },
    "queryAST": {
        "ID": "coursesSingleEntry",
        "KIND": "courses",
        "WHERE": {},
        "OPTIONS": { "COLUMNS": ["coursesSingleEntry_year"] }
    }
}
